custom:
  topic:
    doctor:
      posted: PostedDoctorTopic
      modified: ModifiedDoctorTopic
      deleted: DeletedDoctorTopic
      input-event: InputEventDoctorTopic
    patient:
      posted: PostedPatientTopic
      modified: ModifiedPatientTopic
      deleted: DeletePatientTopic
      input-event: InputEventPatientTopic
      
spring:
  kafka:
    url: localhost:9095
    consumer:
        auto-offset-reset: earliest
        group-id: clinic-group-id
        group-id-test: test-clinic-group-id
    timeout: 6000     
  data:
    mongodb:
      host: localhost
      port: 27017
      database: clinic-ddbb
  cache.type: NONE
  
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.0
        
logging:
  level:
    root: DEBUG
    kafka: OFF
    org.apache: ERROR
    org.springframework: ERROR
